### ISSUE TITLE
Houdini-Svelte plugin not found

### ISSUE THREAD

**Issue by fobtac** [spences10/sveltekit-vendure-commerce#510]
After initial clone into repo and instillation of dependencies, I am unable to start the development server. I'm getting the following error: 

error when starting dev server:
Error: Could not find plugin: houdini-svelte. Are you sure its installed? If so, please open a ticket on GitHub.

This happens after setting up my Vendure server, running it locally, then attempting a fresh instillation of sveltekit-vendure-commerce. I've attempted reinstalling houdini-svelte, both with --legacy-peer-deps and with --force. houdindi-svelte is showing up in my project dependency files and my plugins, so I'm not sure what I may be missing. Any help would be much appreciated. Thank you!

![error1](https://github.com/spences10/sveltekit-vendure-commerce/assets/138246812/4cb1b75f-79ef-4cae-a88f-26c4246c214b)
![error2](https://github.com/spences10/sveltekit-vendure-commerce/assets/138246812/d70d8ce8-9484-43e8-b550-78cd2d907828)
![error3](https://github.com/spences10/sveltekit-vendure-commerce/assets/138246812/ac3b1fb0-9934-44f3-9a3b-e5206a3ea82f)

**Comment by spences10** [comment]
hey @fobtac this repo is only in maintenance and is in dire need of updating, it uses SvelteKit v1 and Svelte v4

There's been many changes in both Houdini and SvelteKit since this was last worked on, apologies if you have wasted any time on this

I'm not planning on updating this anytime soon just an FYI
